steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/summarizer-api', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/summarizer-api']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'summarizer-api',
      '--image', 'gcr.io/$PROJECT_ID/summarizer-api',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY  # You can also use 'NONE' if you want no logging
  logsBucket: gs://my-cloud-build-model  # Update this with your bucket name
