name: Build and Deploy Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t r-summarizer .

    - name: Run Docker Container
      run: |
        docker run -d -p 8000:8000 r-summarizer

